export const demoServices = [
  {
    id: "demo-service-1",
    title: "SMM strategiya",
    slug: "smm-strategiya",
    description: "Brend pozitsiyasi, kontent yo'nalishi va sotuvga olib boruvchi oylik reja.",
    icon: "Target",
    imageUrl: null,
    features: ["Audit va raqobatchi tahlili", "Kontent rubrikalari", "KPI va roadmap"],
    isActive: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-service-2",
    title: "Kontent production",
    slug: "kontent-production",
    description: "Reels, post, story va visual identika uchun premium ijodiy ishlab chiqarish.",
    icon: "Sparkles",
    imageUrl: null,
    features: ["Reels ssenariy", "Dizayn paket", "Copywriting"],
    isActive: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-service-3",
    title: "Target reklama",
    slug: "target-reklama",
    description: "Instagram va Meta Ads orqali lead va savdoni oshirishga qaratilgan kampaniyalar.",
    icon: "Megaphone",
    imageUrl: null,
    features: ["Pixel/analytics", "A/B test", "Haftalik optimizatsiya"],
    isActive: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const demoPortfolio = [
  {
    id: "demo-portfolio-1",
    title: "Beauty studio uchun 3x lead o'sishi",
    slug: "beauty-studio-lead-growth",
    client: "Lumi Beauty",
    category: "Beauty",
    summary: "Kontent formatlarini yangilab, reklama funnelini soddalashtirdik.",
    challenge: "Lead narxi yuqori va profil konversiyasi past edi.",
    solution: "Reels seriyasi, UGC format va segmentlangan target kampaniyalar ishga tushirildi.",
    results: ["3.1x ko'proq lead", "-42% lead narxi", "18 kun ichida 120+ ariza"],
    imageUrl: null,
    instagramUrl: null,
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-portfolio-2",
    title: "Restoran uchun bronlar oqimi",
    slug: "restoran-bronlar-oqimi",
    client: "Aurum Dining",
    category: "Restaurant",
    summary: "Premium visual uslub va geotarget orqali kechki bronlar oshirildi.",
    challenge: "Vizual uslub tarqoq va bron olish jarayoni noaniq edi.",
    solution: "Menu, interyer va mijoz tajribasiga asoslangan kontent liniyasi yaratildi.",
    results: ["2.4x bron", "31% engagement", "Haftalik sold-out kunlar"],
    imageUrl: null,
    instagramUrl: null,
    isFeatured: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const demoPricing = [
  {
    id: "demo-pricing-1",
    name: "Start",
    slug: "start",
    price: "$299/oy",
    description: "Yangi bizneslar uchun toza start.",
    features: ["12 post", "8 story", "Oylik kontent reja", "Basic reporting"],
    isPopular: false,
    isActive: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-pricing-2",
    name: "Growth",
    slug: "growth",
    price: "$599/oy",
    description: "Kontent va reklama birga ishlaydigan paket.",
    features: ["20 post/reels", "Daily story", "Target setup", "Haftalik hisobot"],
    isPopular: true,
    isActive: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-pricing-3",
    name: "Scale",
    slug: "scale",
    price: "$999/oy",
    description: "Savdo funnel va performance growth uchun.",
    features: ["Full production", "Meta Ads boshqaruvi", "CRM lead tracking", "Strategik sessiya"],
    isPopular: false,
    isActive: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const demoTestimonials = [
  {
    id: "demo-testimonial-1",
    name: "Dilnoza Karimova",
    role: "Founder",
    company: "Lumi Beauty",
    content: "Muradovs_.smm bilan profilimiz ancha premium ko'rinish oldi va arizalar soni sezilarli oshdi.",
    rating: 5,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-testimonial-2",
    name: "Jasur Aliyev",
    role: "Marketing manager",
    company: "Aurum Dining",
    content: "Jamoa strategik fikrlaydi, faqat post chiqarish emas, biznes natijaga ishlaydi.",
    rating: 5,
    imageUrl: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const demoFaqs = [
  {
    id: "demo-faq-1",
    question: "Natijani qancha vaqtda ko'ramiz?",
    answer: "Odatda ilk signal 2-4 haftada ko'rinadi, barqaror o'sish uchun 3 oy tavsiya qilamiz.",
    isActive: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "demo-faq-2",
    question: "Reklama byudjeti paketga kiradimi?",
    answer: "Yo'q, reklama byudjeti alohida Meta Ads hisobingizdan sarflanadi.",
    isActive: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const demoPosts = [
  {
    id: "demo-blog-1",
    title: "Instagram profilini sotuvga tayyorlash uchun 7 qadam",
    slug: "instagram-profilini-sotuvga-tayyorlash",
    excerpt: "Bio, highlights, kontent va CTA orqali profil konversiyasini oshirish yo'llari.",
    content:
      "Instagram profilingiz mini landing page vazifasini bajaradi. Avval auditoriyangiz kimligini aniqlang, bio'da aniq taklif yozing, highlights'ni xizmatlar va natijalar bo'yicha tartiblang. Har bir post foyda, ishonch yoki harakatga chaqirish vazifasini bajarishi kerak.",
    imageUrl: null,
    tags: ["Instagram", "SMM", "Konversiya"],
    isPublished: true,
    publishedAt: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
